### ISSUE TITLE
How exciting!

### ISSUE THREAD

**Issue by chrisdone** [paf31/runpurs-hs#24]
Oddly I’ve wanted something like this for a while. 

* External facing DSLs (like my jl) within Haskell
* For a “close enough to Haskell that you could embed it with TH”
* Using PureScript for server side dev instead of Haskell potentially
* Testing my client side code with a Haskell test suite - something I am currently doing with QuickJS
* Server-side rendering of client side code
* Exploring hot reloading 

So thanks for sharing this, it opens up a lot of possibilities.

**Comment by chrisdone** [comment]
It’s also a huge burden to distribute a Haskell interpreter. But PureScript is tiny by comparison. So it can really shine for scripting language use case. Aside from that, its core language is far smaller and far more stable, making it great for user facing scripting. Haskell changes every 5 minutes.

**Comment by paf31** [comment]
Thanks Chris! Those are definitely a lot of the same sort of motivations that I had.

Seems like there are enough rough edges with production Haskell (no debugger, hot reloading, compile times, complicated deployment cycles, etc.) but I feel like there's so often a split between really "core" code, and the glue code (which can make up 80% or more of the total code size), and I'm personally willing to sacrifice some type safety and raw performance to get back some of those missing things for the glue code part of my code.

**Comment by chrisdone** [comment]
I hear that! I'll watch this repo and share any experiments.

**Comment by chrisdone** [comment]
Thinking aloud, in case any thoughts overlap with anyone else.

I might even revive Hell (https://github.com/chrisdone/hell) as a “pinned” PureScript plus process launching functions using this. 🤔 (I consider PureScript and GHC to be dialects of “Haskell”, why not Hell) Forget all the quoted shell nonsense.

Bash is a mess but stable, Python is better but unstable, Dhall is nice but too limited. 

PS plus a few handy functions could be really nice. The kind of tool where if I run the same script in 3 or 5 years it’ll still work exactly the same just like bash, with append-only language/prelude policy, all given functions namespaced under Hell.foo, and breaking changes requiring a new binary name like hell2, hell3, etc. I’d have to extend the import syntax to support HTTPS URLs with SHA256 hashes, but aside from that there wouldn’t really be any changes needed.
